src/main/java/com/capitalone/dashboard/ApiSettings.java, src/main/java/com/capitalone/dashboard/evaluator/DeployEvaluator.java, src/main/java/com/capitalone/dashboard/service/FeatureMetricServiceImpl.java, src/test/java/com/capitalone/dashboard/evaluator/DeployEvaluatorTest.java
=> extended deployment script handling

src/main/java/com/capitalone/dashboard/evaluator/DeployEvaluator.java
=> updated comment

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java, src/main/java/com/capitalone/dashboard/response/PerformanceTestAuditResponse.java
This PR is created to include perf risk assessment status in perf audit response.
=> Add perf risk assessment status in perf audit response

pom.xml
=> Increment Version v3.1.2-SNAPSHOT

README.md
=> added lgtm badges

.github/workflows/maven-pr-checks.yml
=> remove exclude path causing PR checks to fail

.github/workflows/maven-snapshot-release.yml
**Affects:**  all versions.
---
=> fix release to snapshot repository

pom.xml
=> update the version of core

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java, src/test/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluatorTest.java
This PR is created to enhance Performance Test Audit API added with Performance Risk Assessment.
=> Performance Test Audit API enhancement

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
Fixed a bug where it throws exception if there's no reviews for a PR
=> Fixed a bug in CodeReviewEvaluator

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
=> merge commit - included in commits related to PR

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/main/java/com/capitalone/dashboard/response/CodeReviewAuditResponseV2.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> add commit_after_pr_merge to PR level

src/main/java/com/capitalone/dashboard/evaluator/ArtifactEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/BuildEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/CodeQualityEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/DeployEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/Evaluator.java, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/DeployEvaluatorTest.java
This PR is created to distinguish deploy audit among prod and non-prod env data.
=> Deploy Audit process update 

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/main/java/com/capitalone/dashboard/response/CodeReviewAuditResponseV2.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> flag specific commits by unauth users

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> update logic to avoid flagging unauth user commit with approved message

pom.xml
updated core version to 3.6.0
---
=> updated core version to 3.6.0

pom.xml
=> automated releases to maven central

pom.xml
=> fix vulnerabilities for transitive dependencies

src/main/java/com/capitalone/dashboard/config/WebSecurityConfig.java
This PR is created to permit GET /auditresult calls from hygieia ui.
=> allow auditresult get rest calls

src/main/java/com/capitalone/dashboard/evaluator/Evaluator.java, src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluator.java, src/test/java/com/capitalone/dashboard/service/DashboardAuditServiceTest.java, src/test/resources/component/component.json
=> Audit response specific to testType

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
=> Merge commit - Audit validation

pom.xml, src/test/resources/expected/CodeQuality.json
=> Increment core version to 3.7.3

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> Exclude bots from LDAPDN check

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
=> Add null check for authorType check

pom.xml, src/main/java/com/capitalone/dashboard/ApiSettings.java, src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java, src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegecyTest.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> Allow all service account to bump version

pom.xml, src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java
=> Update ldapdn audit logic

pom.xml, src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java
=> Revert "Update ldapdn audit logic"

pom.xml, src/main/java/com/capitalone/dashboard/ApiSettings.java, src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java, src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegecyTest.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> Revert "Allow all service account to bump version"

src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
due to treating change requests as reviews.
=> fixed Bug - Violation has incorrect message

pom.xml
=> Update audit api version

pom.xml, src/main/java/com/capitalone/dashboard/ApiSettings.java, src/main/java/com/capitalone/dashboard/evaluator/ArtifactEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/ArtifactEvaluatorTest.java, src/test/java/com/capitalone/dashboard/service/DashboardAuditServiceTest.java
=> Artifact audit - include third party check

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/CodeQualityEvaluator.java
PR to fix incorrect value of lastExecutionTime in sonar missing scan details.
=> sonar missing scan details' lastExecutionTime update 

src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
=> fixed audit-api logging

pom.xml
=> increment audit api version to 3.5.1

README.md
Updates to README to not go to gh-pages
=> Update to api-audit README

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/ArtifactEvaluator.java
=> nextGen Audit - Artifact - NO_ACTIVITY

src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java
=> Librarypolicy audit - get last scanned result

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
code review audit - repo error validation done against the time range, pull requests, commits.
=> code review audit - repo error validation

pom.xml, src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
=> log the request parameters of GET requests

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java
=> LibraryPolicy audit - get latest scan by evaluation time

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java
=> Librarypolicy Audit - get latest scan with evaluation time

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java
=> LibraryPolicyResult audit - INVALID SCAN

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/AutoDiscoverEvaluator.java, src/main/java/com/capitalone/dashboard/model/DashboardAuditModel.java, src/main/java/com/capitalone/dashboard/request/DashboardAuditRequest.java, src/main/java/com/capitalone/dashboard/response/AutoDiscoverAuditResponse.java, src/main/java/com/capitalone/dashboard/rest/DashboardAuditController.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditService.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java, src/test/java/com/capitalone/dashboard/service/DashboardAuditServiceTest.java
=> Autodiscover audit

pom.xml, src/main/java/com/capitalone/dashboard/ApiSettings.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/common/TestConstants.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> Merge commit from target branch changes

pom.xml, src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java, src/main/java/com/capitalone/dashboard/rest/CodeReviewAuditController.java, src/main/java/com/capitalone/dashboard/rest/DashboardAuditController.java
- Stop logging of responses in `audit_requests` collection.
- added transaction logging for audit requests.
- removed logging of ping requests.
=> logging and auditlogging changes

pom.xml, src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
=> LoggingFilter - removed parsing

pom.xml
=> updated core version to 3.14.16

pom.xml
=> updated audit version to 3.5.14

pom.xml
=> updated pom to 3.5.15

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluatorTest.java
=> Staticsecurityscan - Audit validations

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluator.java, src/main/java/com/capitalone/dashboard/model/DashboardAuditModel.java, src/main/java/com/capitalone/dashboard/response/InfrastructureAuditResponse.java
=> Infrastructure scan - audit 

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluator.java
=> InfrastructureScan - validation 

pom.xml, src/test/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluatorTest.java
=> Infrastructure Audit - Unit tests

pom.xml
=> Updated core version - Codequality sev counts

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
code review audit enhancement to run through all patterns of commit logs
=> code review audit enhancement

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluator.java, src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java, src/test/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluatorTest.java
=> infra scan audit enhancement

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluatorTest.java
=> StaticSecurity Audit - Vul count check

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/Evaluator.java, src/main/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluatorTest.java
Infra audit distinct by instanceId
=> Infra audit distinct by instanceId

pom.xml, src/main/java/com/capitalone/dashboard/request/DashboardAuditRequest.java, src/main/java/com/capitalone/dashboard/rest/DashboardAuditController.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditService.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java, src/test/java/com/capitalone/dashboard/common/TestUtils.java, src/test/java/com/capitalone/dashboard/service/DashboardAuditServiceTest.java, src/test/resources/audit_reports/audit_reports.json
=> artifact audit lookup

pom.xml, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java
=> audit lookup update

pom.xml, src/main/java/com/capitalone/dashboard/rest/DashboardAuditController.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditService.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java, src/test/java/com/capitalone/dashboard/service/DashboardAuditServiceTest.java
=> lookup audit updated

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluatorTest.java
ssa audit time range filter removed
=> ssa audit time range filter removed

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/ArtifactEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/AutoDiscoverEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/BuildEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/CodeQualityEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/DeployEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/Evaluator.java, src/main/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluator.java, src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java, src/main/java/com/capitalone/dashboard/rest/DashboardAuditController.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditService.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java, src/test/java/com/capitalone/dashboard/service/DashboardAuditServiceTest.java, src/test/resources/collector_items/items.json, src/test/resources/component/component.json
artifact lookup filter by identifier name
=> artifact lookup filter by identifier name

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java, src/test/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluatorTest.java
=> LIBRARY_POLICY_OK validations

pom.xml, src/main/java/com/capitalone/dashboard/ApiSettings.java, src/main/java/com/capitalone/dashboard/exception/ExceptionHandlerAdvice.java, src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
- Added the capability to toggle DB serialization of requests using property `logRequest` 
- Added Exception Handling for generic exceptions
=> Toggle the serialization of requests using a property

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
additional check for direct commit
=> additional check for direct commit

pom.xml
=> hygieia core upgrade - AuditType CONTAINER_SCAN

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/Evaluator.java, src/main/java/com/capitalone/dashboard/model/GitComponent.java, src/main/java/com/capitalone/dashboard/util/ConversionUtils.java, src/test/java/com/capitalone/dashboard/common/ConversionUtilsTest.java
=> Audit based on altIdentifier

pom.xml, src/test/java/com/capitalone/dashboard/common/ConversionUtilsTest.java
=> Audit based on altIdentifier - unit tests

pom.xml
=> Revert "core update - 3.15.26"

pom.xml, src/test/java/com/capitalone/dashboard/common/ConversionUtilsTest.java
=> Revert "Audit based on altIdentifier - unit tests"

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/Evaluator.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java
=> getDashboard - Remove ignorecase check 

pom.xml, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
=> Add test cases to mergeCommitAfterReviews

pom.xml
=> Update pom.xml 3.7.19-SNAPSHOT

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java, src/main/java/com/capitalone/dashboard/response/AuditReviewResponse.java, src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
Will identify PR if a PR has been automerged and update a boolean for that in the gitRequest collection.
=> Adding code to fix SOD Violation on Automerged PR's

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
=> Don't count skipped tests against threshold

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
- Added boolean to help break from for loop
- Added filter to shorten list of items that need to be iterated through
=> Added boolean and filtering to help audit time 

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
=> Fix skipped test logic

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/FeatureTestResultEvaluator.java
=> Account for unknown status test cases in threshold

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java
=> Update pom.xml, display cvss3 results for library_policy audit

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java
=> Add informative statuses instead of empty responses

pom.xml, src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java
=> Account for {} in auditResponse

pom.xml, src/main/java/com/capitalone/dashboard/evaluator/InfrastructureEvaluator.java
=> Handle NPE in filteredForBap and filteredForASV for infra evaluator
